### ISSUE TITLE
input file structure?

### ISSUE THREAD

**Issue by mlynekg3** [FredrikSvenssonUK/tox21_conformal#1]
Dear Fredrik, how is your input file looking. From https://tripod.nih.gov/tox21/challenge/data.jsp I get a file called tox21_10k_data_all.sdf but your code loads in a .csv file.

from 002_RF_LGBM_Prob.py

def Table_Reader(File):
    '''function to read data separated with tab into DF'''
    print('Input file: %s' %str(File))#list input file
    DF=pd.read_csv(File,sep='\t') #read data into dataframe
    print('Input data set size: %s' %str(DF.shape))
    return DF

Many thanks, br Georg.

**Comment by FredrikSvenssonUK** [comment]
Hi Georg,

Beofre applying the prediction scripts we provided, the sd file from the website needs to be processed. We outline this briefly in the methods.
"The compound structures were standardized using RDKit. RDKit molecular descriptors (consisting of 97 structural and physicochemical properties) and 1024 bits Morgan fingerprints (FP) (an extended-connectivity FP)26 with radius=4 were calculated for all structures. The values of molecular descriptors were scaled to the range between 0 and 1 using the MinMaxScaler function from the scikit-learn package."

I will have a look back at my files and see if I can upload something. 

Hope that helps.

Best wishes,
Fredrik

**Comment by mlynekg3** [comment]
Dear Fredierik, thanks for answering that fast. It would be nice if you could find something. I am a structural biologist, starting to learn programming and for me seeing different pieces of code helps me to learn faster than struggling writing my own code. I guess/hope this will change soon.
Br, Georg.

**Comment by FredrikSvenssonUK** [comment]
This is not nessesarily exactly what we used for the paper but it will give you an idea about what you need.
It will read an sd-file and save a file with the required properties for the machine learning.

```
#imports
from rdkit import Chem
from rdkit.ML.Descriptors.MoleculeDescriptors import MolecularDescriptorCalculator
import sys

try:
    sys.argv[1]
except IndexError:
    print "You need to specify an input file"
    sys.exit(1)
try:
    sys.argv[2]
except IndexError:
    output_path =sys.argv[1]+".rdkit"

#Set up what descriptors to calculate
calc = MolecularDescriptorCalculator(['Chi0','Chi0n','Chi0v','Chi1',\
'Chi1n','Chi1v','Chi2n','Chi2v','Chi3n','Chi3v','Chi4n','Chi4v',\
'EState_VSA1','EState_VSA10','EState_VSA11','EState_VSA2','EState_VSA3',\
'EState_VSA4','EState_VSA5','EState_VSA6','EState_VSA7','EState_VSA8',\
'EState_VSA9','FractionCSP3','HallKierAlpha','HeavyAtomCount','Ipc',\
'Kappa1','Kappa2','Kappa3','LabuteASA','MolLogP','MolMR','MolWt',\
'NHOHCount','NOCount','NumAliphaticCarbocycles','NumAliphaticHeterocycles',\
'NumAliphaticRings','NumAromaticCarbocycles','NumAromaticHeterocycles',\
'NumAromaticRings','NumHAcceptors','NumHDonors','NumHeteroatoms',\
'NumRotatableBonds','NumSaturatedCarbocycles','NumSaturatedHeterocycles',\
'NumSaturatedRings','PEOE_VSA1','PEOE_VSA10','PEOE_VSA11','PEOE_VSA12',\
'PEOE_VSA13','PEOE_VSA14','PEOE_VSA2','PEOE_VSA3','PEOE_VSA4','PEOE_VSA5',\
'PEOE_VSA6','PEOE_VSA7','PEOE_VSA8','PEOE_VSA9','RingCount','SMR_VSA1',\
'SMR_VSA10','SMR_VSA2','SMR_VSA3','SMR_VSA4','SMR_VSA5','SMR_VSA6','SMR_VSA7',\
'SMR_VSA8','SMR_VSA9','SlogP_VSA1','SlogP_VSA10','SlogP_VSA11','SlogP_VSA12',\
'SlogP_VSA2','SlogP_VSA3','SlogP_VSA4','SlogP_VSA5','SlogP_VSA6','SlogP_VSA7',\
'SlogP_VSA8','SlogP_VSA9','TPSA','VSA_EState1','VSA_EState10','VSA_EState2',\
'VSA_EState3','VSA_EState4','VSA_EState5','VSA_EState6','VSA_EState7',\
'VSA_EState8','VSA_EState9'])

nms = list(calc.GetDescriptorNames())
suppl = Chem.SDMolSupplier(sys.argv[1])
w = Chem.SmilesWriter(output_path)
w.SetProps(nms)

for mol in suppl:
    if mol is None: continue
    descrs = calc.CalcDescriptors(mol)
    for nm,v in zip(nms,descrs):
        mol.SetProp(nm,str(v))
    w.write(mol)
```
